AUGS:
  FLIP_PROB: 0.5
  MEAN: (0.485, 0.456, 0.406)
  STD: (0.229, 0.224, 0.225)
  CROP_SIZE: (256, 256)
  CONTRASTIVE_ENABLE: False
MODEL:
  NAME: 'efficientnet-b0'
  CLASSIFICATION_FEATURE: 2048
  QUEUE_SIZE: 6400
  LOCAL_ALIGNMENT: False
TRAINING:
  BATCH_SIZE: 32
  LR: 0.001
  SCHEDULER: 'default'
  NUM_WORKERS: 6
  MAX_EPOCHS: 20
DATAS:
  TARGET: ['Face2Face']
  SOURCE: "FaceSwap"
  WITH_FREQUENCY: True
  DATA_RATIO: 1.0
DOMAIN_FINETUNING:
  EPOCH: 10
  ENABLE: False
  LR: 0.001
  DISCRIMINATOR: True

