AUGS:
  FLIP_PROB: 0.5
  MEAN: (0.485, 0.456, 0.406)
  STD: (0.229, 0.224, 0.225)
  CROP_SIZE: (224, 224)
  CONTRASTIVE_ENABLE: False
MODEL:
  CLASSIFICATION_FEATURE: 1024
  QUEUE_SIZE: 3200
  LOCAL_ALIGNMENT: False
TRAINING:
  BATCH_SIZE: 32
  LR: 0.001
DATAS:
  TARGET: ['Deepfakes']
  SOURCE: "Face2Face"
  WITH_FREQUENCY: True

